openapi: 3.0.0
components:
  securitySchemes:
    jwtCookieAuth:
      type: apiKey
      in: cookie
      name: auth_token
      description: Use JWT token in a cookie for authentication
info:
  title: Car Site Card API
  version: 1.0.0
  description: API for managing cars on Car Site Api
servers:
  - url: http://localhost:5004
    description: Development server
paths:
  "/api/car":
    post:
      summary: Create a new car
      security:
        - jwtCookieAuth: [] 
      tags:
        - Cars
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                make:
                  type: string
                model:
                  type: string
                version:
                  type: string
                price:
                  type: number
                mileage:
                  type: number
                color:
                  type: string
                transmission:
                  type: string
                year:
                  type: number
                active:
                  type: boolean
                vin:
                  type: string
                carImages:
                  type: array
                  items:
                    type: string
                    format: binary
                address:
                  type: object
                  properties:
                    state:
                      type: string
                    city:
                      type: string
                    zipCode: 
                      type: string
                    street:
                      type: string
      responses:
        "201":
          description: Make created successfully
          # content:
          #   application/json:
          #     schema:
          #       type: array
          #       items:
          #         type: object
          #         properties:
          #           id:
          #             type: string
          #           makeName:
          #             type: string
          #           origin:
          #             type: string
          #           makeLogo:
          #             type: string
          #           active:
          #             type: boolean
          #           createdAt:
          #             type: string